services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}
    restart: unless-stopped
    volumes:
      - .:/docker_dash
    environment:
      - DEBUG_MODE=False
      - "VIRTUAL_HOST=${VIRTUAL_HOST}"
      - "VIRTUAL_PORT=${VIRTUAL_PORT}"
    expose:
      - "${VIRTUAL_PORT}"
    deploy:
      resources:
        limits:
          cpus: "${LIMIT_CPU}"
          memory: "${LIMIT_MEM}"
    networks:
      - default

networks:
  default:
    name: "${NETWORK}"
    external: true